name: Feature request
description: Sugira uma melhoria ou funcionalidade
labels: [enhancement]
body:
  - type: textarea
    id: problema
    attributes:
      label: Problema/motivação
      description: Qual problema isso resolve?
    validations:
      required: true
  - type: textarea
    id: proposta
    attributes:
      label: Proposta
      description: Descreva a solução desejada e alternativas consideradas.
    validations:
      required: true
  - type: textarea
    id: impacto
    attributes:
      label: Impacto e trade-offs
  - type: textarea
    id: docs
    attributes:
      label: Documentação
      description: Quais docs precisam de atualização? (usecases/usegraphs/roadmap)


